In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("gpu avialable")
  print(f":using Gpu: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

gpu avialable
:using Gpu: Tesla T4


<h2> Creating a Tensor </h2>

In [ ]:
#using empty
torch.empty(2,3)

tensor([[-1.0514e+14,  4.4879e-41, -1.0514e+14],
        [ 4.4879e-41,  0.0000e+00,  0.0000e+00]])

In [ ]:
 a = torch.empty(2,3)
 type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

<h3> Other Ways </h3>

In [ ]:
print ("using arange ->",torch.arange(0,10))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
 torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(4,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

<h1> Tensor Shape </h1>

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
#copying a tensor

torch.empty_like(x)

tensor([[8027140907415206688, 7018332503360695925, 7810686650323137388],
        [8317408971626606689, 3544668456162966050,        435892599095]])

In [ ]:
 torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#torch.rand_like(x) #dosent work as it generates float and x is integer
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

<h2> Tensor DataType </h2>

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
#change Datatype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

<h2> Mathmetical Operations </h2>

In [ ]:
#Scaler operations

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
x + 2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
x*2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [ ]:
x/2

tensor([[0.3559, 0.3938],
        [0.2092, 0.4507]])

In [ ]:
x * 100 #integer devision
x//3

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
x%2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

<h3> Element Wise Operations </h3>

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
a

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])

In [ ]:
b

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])

In [ ]:
a + b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
a /b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
torch.abs(c) #absolute

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(c) #negative

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [ ]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

<h4> Reduction Operation </h4>

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10)

In [ ]:
e

tensor([[8, 0, 7],
        [0, 0, 9]])

In [ ]:
torch.sum(e)

tensor(24)

In [ ]:
torch.sum(e,dim=0)

tensor([ 8,  0, 16])

In [ ]:
torch.sum(e,dim=1)

tensor([15,  9])

In [ ]:
#torch.mean(e) #work only on float

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [ ]:
f

tensor([[5., 7., 3.],
        [9., 4., 0.]])

In [ ]:
torch.mean(f)

tensor(4.6667)

In [ ]:
torch.median(e)

tensor(0)

In [ ]:
torch.max(e)

tensor(9)

In [ ]:
torch.min(e)

tensor(0)

In [ ]:
torch.prod(e)

tensor(0)

In [ ]:
torch.var(f) #float ,complex supported

tensor(9.8667)

In [ ]:
torch.std(f) #float complex only

tensor(3.1411)

In [ ]:
torch.argmax(e) #position of biggest item

tensor(5)

In [ ]:
torch.argmax(f)

tensor(3)

In [ ]:
torch.argmin(f)

tensor(5)

<h3> Matrix Multiplication </h3>

In [ ]:
g = torch.randint(size=(2,3),low=0,high=10)
h = torch.randint(size=(3,2),low=0,high=10)
g

tensor([[5, 7, 5],
        [9, 9, 7]])

In [ ]:
h

tensor([[5, 9],
        [8, 9],
        [7, 9]])

In [ ]:
#multiplication
torch.matmul(g,h)

tensor([[116, 153],
        [166, 225]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
g

tensor([[5, 7, 5],
        [9, 9, 7]])

In [ ]:
torch.transpose(g,0,1) #dimension in which to transpose

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [ ]:
"""

#determinant
torch.det(g)
torch.inverse(g)
#squear matrix needed

"""

'\n\n#determinant\ntorch.det(g)\ntorch.inverse(g)\n#squear matrix needed\n\n'

<h3> Comparison Operations </h3>

In [ ]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low=0,high=10)

In [ ]:
i

tensor([[2, 6, 7],
        [7, 8, 3]])

In [ ]:
j

tensor([[6, 1, 5],
        [5, 0, 4]])

In [ ]:
#greater then
i > j

tensor([[False,  True,  True],
        [ True,  True, False]])

In [ ]:
i < j

tensor([[ True, False, False],
        [False, False,  True]])

In [ ]:
i == j

tensor([[False, False, False],
        [False, False, False]])

<h3> Special Function </h3>

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10)
k

tensor([[7, 4, 1],
        [5, 7, 4]])

In [ ]:
torch.log(k)

tensor([[1.9459, 1.3863, 0.0000],
        [1.6094, 1.9459, 1.3863]])

In [ ]:
torch.sqrt(k)

tensor([[2.6458, 2.0000, 1.0000],
        [2.2361, 2.6458, 2.0000]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9991, 0.9820, 0.7311],
        [0.9933, 0.9991, 0.9820]])

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10,dtype = torch.float32)
torch.softmax(k,dim=0) #float type need

tensor([[0.0067, 0.9526, 0.0474],
        [0.9933, 0.0474, 0.9526]])

In [ ]:
torch.relu(k)

tensor([[3., 4., 2.],
        [8., 1., 5.]])

<h1> Inplace operations </h1>

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [ ]:
m + n #result is in new tensor so occupy memory

tensor([[1.0595, 1.3539, 1.4522],
        [0.9133, 0.6129, 1.0610]])

In [ ]:
m.add_(n)

tensor([[1.0595, 1.3539, 1.4522],
        [0.9133, 0.6129, 1.0610]])

In [ ]:
m

tensor([[1.0595, 1.3539, 1.4522],
        [0.9133, 0.6129, 1.0610]])

In [ ]:
m.relu_() #  _  inplace operation

tensor([[1.0595, 1.3539, 1.4522],
        [0.9133, 0.6129, 1.0610]])

In [ ]:
m

tensor([[1.0595, 1.3539, 1.4522],
        [0.9133, 0.6129, 1.0610]])

<h2> Copying a Tensor </h2>

In [ ]:
a = torch.rand(2,3)

In [ ]:
b = a

In [ ]:
b

tensor([[0.6979, 0.5729, 0.1005],
        [0.2548, 0.7437, 0.2597]])

In [ ]:
a

tensor([[0.6979, 0.5729, 0.1005],
        [0.2548, 0.7437, 0.2597]])

In [ ]:
a[0][0] = 3

In [ ]:
a

tensor([[3.0000, 0.5729, 0.1005],
        [0.2548, 0.7437, 0.2597]])

In [ ]:
b #changes also in copy assigment operator ka masla

tensor([[3.0000, 0.5729, 0.1005],
        [0.2548, 0.7437, 0.2597]])

In [ ]:
id(a)

135208002625824

In [ ]:
id(b) #same memory location reference pointer same

135208002625824

In [ ]:
#so we use clone
b = a.clone

In [ ]:
a

tensor([[3.0000, 0.5729, 0.1005],
        [0.2548, 0.7437, 0.2597]])

In [ ]:
b

<function Tensor.clone>

In [ ]:
id(a)

135208002625824

In [ ]:
id(b) #diff id now

135207922781056

<h1> Tensor Operation on GPU </h1>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3034, 0.0320, 0.6745],
        [0.2375, 0.3997, 0.9755]], device='cuda:0')

In [ ]:
#moving an existing tensor on GPU
a = torch.rand((2,3))
a

tensor([[0.0786, 0.6076, 0.7724],
        [0.5896, 0.7451, 0.7048]])

In [ ]:
a.to(device)

tensor([[0.0786, 0.6076, 0.7724],
        [0.5896, 0.7451, 0.7048]], device='cuda:0')

In [ ]:
b = a.to(device)

In [ ]:
b + 5 #this operation done on GPU

tensor([[5.0786, 5.6076, 5.7724],
        [5.5896, 5.7451, 5.7048]], device='cuda:0')

In [ ]:
import time

size = 10000

matrix_cpu1 = torch.randn(size,size)
matrix_cpu2 = torch.randn(size,size)
start_time = time.time()
result_cpu = matrix_cpu1.matmul(matrix_cpu2)
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:4f} seconds")

matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

start_time = time.time()
result_gpu = matrix_gpu1.matmul(matrix_gpu2)
torch.cuda.synchronize()
end_time = time.time() - start_time

Time on CPU: 18.721767 seconds


<h2> Reshaping Tensors </h2>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cpu


In [ ]:
a = torch.ones(4,4)

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten() #1d tensor

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#permute
b = torch.rand(2,3,4)
b

tensor([[[0.1242, 0.6289, 0.5101, 0.5644],
         [0.1518, 0.1112, 0.3145, 0.4248],
         [0.2501, 0.3677, 0.0963, 0.7464]],

        [[0.9105, 0.4108, 0.4745, 0.7880],
         [0.1837, 0.4090, 0.0685, 0.0281],
         [0.5678, 0.9881, 0.7509, 0.4514]]])

In [ ]:
b.permute(2,0,1) # position inverse

tensor([[[0.1242, 0.1518, 0.2501],
         [0.9105, 0.1837, 0.5678]],

        [[0.6289, 0.1112, 0.3677],
         [0.4108, 0.4090, 0.9881]],

        [[0.5101, 0.3145, 0.0963],
         [0.4745, 0.0685, 0.7509]],

        [[0.5644, 0.4248, 0.7464],
         [0.7880, 0.0281, 0.4514]]])

In [ ]:
#unsequeze
c = torch.rand(225,225,3)

In [ ]:
c.unsqueeze(1) #images in batches

tensor([[[[0.9190, 0.9619, 0.6192],
          [0.6122, 0.2260, 0.1544],
          [0.5039, 0.3214, 0.1484],
          ...,
          [0.6120, 0.0663, 0.6734],
          [0.4417, 0.3146, 0.8053],
          [0.7048, 0.4543, 0.9502]]],


        [[[0.0246, 0.3231, 0.1673],
          [0.3676, 0.8912, 0.6468],
          [0.0862, 0.7145, 0.6133],
          ...,
          [0.5969, 0.0486, 0.7614],
          [0.7822, 0.2061, 0.1911],
          [0.8045, 0.9420, 0.6066]]],


        [[[0.3304, 0.0560, 0.6505],
          [0.5665, 0.5955, 0.9332],
          [0.7912, 0.5859, 0.4420],
          ...,
          [0.4181, 0.5141, 0.1094],
          [0.8881, 0.6626, 0.9994],
          [0.4920, 0.9353, 0.4107]]],


        ...,


        [[[0.0114, 0.7706, 0.9146],
          [0.0317, 0.3726, 0.6466],
          [0.2881, 0.6236, 0.9859],
          ...,
          [0.5407, 0.7329, 0.9720],
          [0.4941, 0.2504, 0.5054],
          [0.5762, 0.1322, 0.9467]]],


        [[[0.4289, 0.7226, 0.7649],
         

In [ ]:
d = torch.rand(1,120)
d.squeeze(0).shape

torch.Size([120])

<h2> Numpy and PyTorch </h2>

In [ ]:
import numpy as np

In [ ]:
#we can convert
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])